### ISSUE TITLE
.NET 7.0 support

### ISSUE THREAD

**Issue by Typiqally** [Typiqally/epsilon#44]
.NET 7.0 just released, meaning we should update at least the CLI to support this newer version, as the CLI is runtime dependent. I think we should also think about multiversional .NET support, meaning we should support multiple .NET versions such as 5, 6 and 7.

**Comment by NealGeilen** [comment]
Of course, we should look to the future and expand the supported versions.
I just don't like the idea to build support for versions that are no longer [supported](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core) by Microsoft. 

So I would like to suggest having the focus on .NET 6.0 because it has long time support. 
and add .NET 7.0  support because it's the future.

**Comment by Typiqally** [comment]
Agreed, I didn't realize that .NET 5.0 was already no longer being supported.

**Comment by Typiqally** [comment]
As I see it, we have two options:

1. We could create multiple release binaries each with their own runtime support, which doesn't scale very well.

2. Or we could release binaries with the runtime built into it, which increases the file size of each binary.

In my opinion, the latter is better, since we have more control over how we want to support Epsilon and which .NET features we want to use.
